language: python

os:
 - linux
 - osx

python:
 - pypy
 - pypy3
 - 2.7
 - 3.3
 - 3.4
 - 3.5

before_install:
 - export PATH=$PATH:~/.local/bin:~/bin
 - if [[ $TRAVIS_OS_NAME == "osx" ]]; then brew update; fi
 - if [[ $TRAVIS_OS_NAME == "osx" ]]; then brew install python; fi
 - if [[ $TRAVIS_OS_NAME == "osx" ]]; then pip install -U setuptools virtualenv; fi

install:
 - python setup.py install

script:
 - python setup.py test

matrix:
  allow_failures:
    - os: osx
